print("hello world")
print("hello Rajesh")
print("hello Goyal")
print("hello not again")
print("hello not again")
print("hello not again")
print("hello not again")
print("hello not again")
print("hello not again")
print("hello not again")
print("hello not again")
